# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6041dee7b0e6855ec0caab3369a4fd79b018bfbd1b47e5cb35b82ff1aa5b8a154ba30576107420c2b7ef77b532f6b8e8e867acc59699c7b5b6bde964abea4a99

test:
  secret_key_base: 567963f39e9d38adda48431bff8dd2b84df5d6baa7bbf04620047bad7442747574f4ddae54382e3b0e0e5dac8fedc9345b302008880a20fe58849874e48dc9e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
